theme: jekyll-theme-architect
title: [Shranith Linga]
description: [I usually write about latest advances and break throughs in Machine learning. I often write how to use different machine learning frameworks]
