# SITE CONFIGURATION
baseurl: ""
url: "https://shranith.github.io"
name: Machine learning with Shranith
title: ML with Shranith | shranith.github.io # site's title
description: "I like to write on various techniques and tools in the land of NLP and Machine Learning"


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: MLS # blog's title
  avatar: assets/img/triangle.svg # TODO
  favicon: assets/favicon.ico	  # TODO
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: "Deep learning has evolved into a computational mammoth. efficieNN is a dive into how we're beginning to tame this mammoth to work in the palm of our hands"
  header_text_feature_image: assets/img/cover.png # TODO
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true # Make sure you created a feed.xml with feed.xml layout
  email_address: "shranith.linga@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "shranith"
  google_plus:
  instagram:
  keybase:
  linkedin: "http://www.linkedin.com/in/shranith/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: 
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: "UA-121432719-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "shranith-github-io"
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
